import tailwindcssAnimate from 'tailwindcss-animate'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: { center: true, padding: '1.5rem', screens: { '2xl': '1400px' } },
    extend: {
      maxWidth: { content: '1400px' },
      fontFamily: {
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        sans: ['var(--font-body)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      colors: {
        background: 'var(--bg-base)',
        base: 'var(--bg-base)',
        foreground: 'var(--white)',
        card: { DEFAULT: 'var(--bg-card)', foreground: 'var(--white)' },
        panel: 'var(--bg-panel)',
        elevated: 'var(--bg-elevated)',
        popover: { DEFAULT: 'var(--bg-elevated)', foreground: 'var(--white)' },
        primary: { DEFAULT: 'var(--blue)', foreground: 'var(--white)' },
        secondary: { DEFAULT: 'var(--navy)', foreground: 'var(--white)' },
        muted: { DEFAULT: 'var(--bg-panel)', foreground: 'var(--slate)' },
        accent: { DEFAULT: 'var(--bg-elevated)', foreground: 'var(--white)' },
        destructive: { DEFAULT: 'var(--red)', foreground: 'var(--white)' },
        border: 'var(--border)',
        input: 'var(--border-mid)',
        ring: 'var(--blue-light)',
        navy: 'var(--navy)',
        'blue-light': 'var(--blue-light)',
        water: 'var(--water)',
        energy: 'var(--energy)',
        solar: 'var(--solar)',
        ok: 'var(--ok)',
        warn: 'var(--warn)',
        'red-soft': 'var(--red-soft)',
        'ok-soft': 'var(--ok-soft)',
        'warn-soft': 'var(--warn-soft)',
        slate: { DEFAULT: 'var(--slate)', foreground: 'var(--silver)' },
        charcoal: 'var(--charcoal)',
      },
      borderRadius: {
        lg: 'var(--r3)',
        md: 'var(--r2)',
        sm: 'var(--r1)',
        pill: 'var(--r-full)',
      },
      spacing: {
        s1: 'var(--s1)',
        s2: 'var(--s2)',
        s3: 'var(--s3)',
        s4: 'var(--s4)',
        s5: 'var(--s5)',
        s6: 'var(--s6)',
        s8: 'var(--s8)',
        s10: 'var(--s10)',
        s12: 'var(--s12)',
        s16: 'var(--s16)',
      },
      minHeight: { 11: '2.75rem' },
      minWidth: { 11: '2.75rem' },
      boxShadow: { card: 'var(--shadow-card)' },
      transitionDuration: { fast: 'var(--t-fast)', mid: 'var(--t-mid)', slow: 'var(--t-slow)' },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [tailwindcssAnimate],
}
